default_language_version:
  node: 20.18.0

repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.4.0"
    hooks:
    -   id: biome-check
        additional_dependencies: ["@biomejs/biome@1.8.3"]
